export const generateReactCode = (exportData: any): void => {
  const { elements, format, includeStyles, minifyCode } = exportData;
  
  let code = `// Generated by Eternal UI Studio
import React from 'react';
${includeStyles ? "import './GeneratedComponent.css';" : ''}

export interface GeneratedComponentProps {
  className?: string;
}

export const GeneratedComponent: React.FC<GeneratedComponentProps> = ({ className }) => {
  return (
    <div className={\`generated-component \${className || ''}\`}>
`;

  elements.forEach((element: any) => {
    code += `      ${generateReactElement(element, 3, includeStyles)}
`;
  });

  code += `    </div>
  );
};

export default GeneratedComponent;`;

  if (minifyCode) {
    code = code.replace(/\s+/g, ' ').trim();
  }

  downloadFile(code, 'GeneratedComponent.tsx', 'text/typescript');
};

export const generateVueCode = (exportData: any): void => {
  const { elements, includeStyles, minifyCode } = exportData;
  
  let code = `<!-- Generated by Eternal UI Studio -->
<template>
  <div class="generated-component" :class="className">
`;

  elements.forEach((element: any) => {
    code += `    ${generateVueElement(element, 2, includeStyles)}
`;
  });

  code += `  </div>
</template>

<script setup lang="ts">
interface Props {
  className?: string;
}

defineProps<Props>();
</script>

${includeStyles ? `<style scoped>
/* Generated styles */
.generated-component {
  position: relative;
  width: 100%;
}
</style>` : ''}`;

  if (minifyCode) {
    code = code.replace(/\s+/g, ' ').trim();
  }

  downloadFile(code, 'GeneratedComponent.vue', 'text/plain');
};

export const generateHTMLCode = (exportData: any): void => {
  const { elements, includeStyles, minifyCode } = exportData;
  
  let code = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Generated by Eternal UI Studio</title>
  ${includeStyles ? generateHTMLStyles(elements) : ''}
</head>
<body>
  <div class="generated-component">
`;

  elements.forEach((element: any) => {
    code += `    ${generateHTMLElement(element, 2, includeStyles)}
`;
  });

  code += `  </div>
</body>
</html>`;

  if (minifyCode) {
    code = code.replace(/\s+/g, ' ').trim();
  }

  downloadFile(code, 'generated.html', 'text/html');
};

export const downloadJSON = (exportData: any): void => {
  const jsonData = JSON.stringify(exportData, null, 2);
  downloadFile(jsonData, 'project-export.json', 'application/json');
};

const downloadFile = (content: string, filename: string, mimeType: string): void => {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

const generateReactElement = (element: any, indent: number, includeStyles: boolean): string => {
  const indentStr = '  '.repeat(indent);
  const style = includeStyles && element.style 
    ? ` style={${JSON.stringify(element.style)}}` 
    : '';
  
  switch (element.type) {
    case 'text':
      return `${indentStr}<span${style}>${element.props.text || 'Text'}</span>`;
    case 'button':
      return `${indentStr}<button${style}>${element.props.text || 'Button'}</button>`;
    case 'input':
      return `${indentStr}<input type="${element.props.type || 'text'}" placeholder="${element.props.placeholder || ''}"${style} />`;
    default:
      return `${indentStr}<div${style}>{/* ${element.type} */}</div>`;
  }
};

const generateVueElement = (element: any, indent: number, includeStyles: boolean): string => {
  const indentStr = '  '.repeat(indent);
  const style = includeStyles && element.style 
    ? ` :style="${JSON.stringify(element.style)}"` 
    : '';
  
  switch (element.type) {
    case 'text':
      return `${indentStr}<span${style}>{{ ${JSON.stringify(element.props.text || 'Text')} }}</span>`;
    case 'button':
      return `${indentStr}<button${style}>{{ ${JSON.stringify(element.props.text || 'Button')} }}</button>`;
    case 'input':
      return `${indentStr}<input type="${element.props.type || 'text'}" placeholder="${element.props.placeholder || ''}"${style} />`;
    default:
      return `${indentStr}<div${style}><!-- ${element.type} --></div>`;
  }
};

const generateHTMLElement = (element: any, indent: number, includeStyles: boolean): string => {
  const indentStr = '  '.repeat(indent);
  let styleAttr = '';
  
  if (includeStyles && element.style) {
    const styleStr = Object.entries(element.style)
      .map(([key, value]) => `${key.replace(/([A-Z])/g, '-$1').toLowerCase()}: ${value}`)
      .join('; ');
    styleAttr = ` style="${styleStr}"`;
  }
  
  switch (element.type) {
    case 'text':
      return `${indentStr}<span${styleAttr}>${element.props.text || 'Text'}</span>`;
    case 'button':
      return `${indentStr}<button${styleAttr}>${element.props.text || 'Button'}</button>`;
    case 'input':
      return `${indentStr}<input type="${element.props.type || 'text'}" placeholder="${element.props.placeholder || ''}"${styleAttr} />`;
    default:
      return `${indentStr}<div${styleAttr}><!-- ${element.type} --></div>`;
  }
};

const generateHTMLStyles = (elements: any[]): string => {
  return `
  <style>
    .generated-component {
      position: relative;
      width: 100%;
      min-height: 100vh;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    }
    
    .element {
      position: absolute;
    }
    
    /* Add any additional styles based on elements */
  </style>`;
};