'use client'

import React, { useState } from 'react'
import { ProjectExporter } from '@eternal-ui/core/src/export/ProjectExporter'
import { useBuilderStore } from '@/stores/builderStore'
import { Download, Code, Settings, Rocket, FileText, Zap, Layers } from 'lucide-react'

interface ExportConfig {
  projectName: string
  framework: 'react' | 'vue' | 'svelte' | 'angular' | 'next'
  styling: 'tailwind' | 'styled-components' | 'css-modules' | 'sass'
  features: {
    typescript: boolean
    testing: boolean
    accessibility: boolean
    seo: boolean
    pwa: boolean
  }
}

export default function ExportDemo() {
  // Get actual builder state
  const { elements } = useBuilderStore()
  
  const [config, setConfig] = useState<ExportConfig>({
    projectName: 'My Eternal UI Project',
    framework: 'react',
    styling: 'tailwind',
    features: {
      typescript: true,
      testing: true,
      accessibility: true,
      seo: true,
      pwa: false
    }
  })
  
  const [exportResult, setExportResult] = useState<any>(null)
  const [loading, setLoading] = useState(false)
  const [step, setStep] = useState<'config' | 'preview' | 'export'>('config')

  // Convert builder elements to export format
  const convertElementsToComponents = () => {
    return elements.map(element => ({
      name: element.type.charAt(0).toUpperCase() + element.type.slice(1),
      type: element.type,
      props: element.props,
      styling: getElementStyling(element),
      children: element.children || []
    }))
  }

  // Generate styling classes based on element type
  const getElementStyling = (element: any) => {
    switch (element.type) {
      case 'button':
        const variant = element.props.variant || 'default'
        return variant === 'default' 
          ? 'bg-blue-500 hover:bg-blue-600 text-white px-6 py-3 rounded-lg font-semibold'
          : variant === 'outline'
          ? 'border border-gray-300 hover:bg-gray-50 text-gray-700 px-6 py-3 rounded-lg font-semibold'
          : 'bg-red-500 hover:bg-red-600 text-white px-6 py-3 rounded-lg font-semibold'
      
      case 'card':
        return 'bg-white shadow-lg rounded-lg p-6 border border-gray-200'
      
      case 'container':
        const size = element.props.size || 'lg'
        return size === 'full' 
          ? 'w-full px-4'
          : `max-w-screen-${size} mx-auto px-4`
      
      case 'grid':
        const cols = element.props.cols || 3
        const gap = element.props.gap || 4
        return `grid grid-cols-${cols} gap-${gap}`
      
      default:
        return 'p-4 rounded-lg'
    }
  }

  const handleExport = async () => {
    setLoading(true)
    setStep('export')
    
    try {
      const exporter = new ProjectExporter({
        projectName: config.projectName,
        description: `Generated by Eternal UI Studio - ${config.framework} project with ${elements.length} components`,
        version: '1.0.0',
        author: 'Eternal UI User',
        license: 'MIT',
        framework: config.framework,
        styling: config.styling,
        buildTool: 'vite',
        features: {
          ...config.features,
          linting: true,
          i18n: false
        }
      })

      // Use actual components from builder
      const components = convertElementsToComponents()
      console.log('Exporting components:', components)

      const result = await exporter.exportProject(components)
      setExportResult(result)
    } catch (error) {
      console.error('Export failed:', error)
    } finally {
      setLoading(false)
    }
  }

  const downloadAsZip = () => {
    // TODO: Implement ZIP download functionality
    alert('ZIP download coming soon! For now, you can copy the generated code.')
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-10">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center py-4">
            <div className="flex items-center space-x-4">
              <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white p-2 rounded-lg">
                <Rocket className="w-6 h-6" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-gray-900">Eternal UI Studio Export</h1>
                <p className="text-gray-600">Export your design as production-ready code</p>
              </div>
            </div>
            
            {/* Step Indicator */}
            <div className="flex items-center space-x-8">
              {[
                { key: 'config', label: 'Configure', icon: Settings },
                { key: 'preview', label: 'Preview', icon: Code },
                { key: 'export', label: 'Export', icon: Download }
              ].map(({ key, label, icon: Icon }) => (
                <div key={key} className={`flex items-center space-x-2 ${
                  step === key ? 'text-blue-600' : 'text-gray-400'
                }`}>
                  <Icon className="w-5 h-5" />
                  <span className="font-medium">{label}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        
        {/* Builder Preview */}
        <div className="mb-8 bg-white rounded-xl shadow-lg border border-gray-200 overflow-hidden">
          <div className="bg-gray-50 px-6 py-4 border-b border-gray-200">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <Layers className="w-5 h-5 text-blue-600" />
                <h3 className="text-lg font-semibold">Your Design</h3>
              </div>
              <div className="text-sm text-gray-600">
                {elements.length} component{elements.length !== 1 ? 's' : ''} ready to export
              </div>
            </div>
          </div>
          
          <div className="p-6">
            {elements.length > 0 ? (
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {elements.slice(0, 6).map((element, index) => (
                  <div key={element.id} className="border border-gray-200 rounded-lg p-3 bg-gray-50">
                    <div className="flex items-center space-x-2">
                      <span className="text-lg">
                        {element.type === 'button' && '🔘'}
                        {element.type === 'card' && '🃏'}
                        {element.type === 'container' && '📦'}
                        {element.type === 'grid' && '🔲'}
                        {element.type === 'input' && '📝'}
                      </span>
                      <div>
                        <div className="font-medium capitalize">{element.type}</div>
                        <div className="text-xs text-gray-500">
                          {element.props.children || element.props.placeholder || 'Component'}
                        </div>
                      </div>
                    </div>
                  </div>
                ))}
                {elements.length > 6 && (
                  <div className="border border-gray-200 rounded-lg p-3 bg-gray-50 flex items-center justify-center">
                    <span className="text-gray-500">+{elements.length - 6} more</span>
                  </div>
                )}
              </div>
            ) : (
              <div className="text-center py-8">
                <div className="text-4xl mb-4">🎨</div>
                <h4 className="text-lg font-medium text-gray-900 mb-2">No Components Yet</h4>
                <p className="text-gray-600">Go back to the builder to create components first!</p>
              </div>
            )}
          </div>
        </div>

        {step === 'config' && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Configuration Panel */}
            <div className="bg-white rounded-xl shadow-lg p-6 border border-gray-200">
              <h2 className="text-xl font-semibold mb-6 flex items-center">
                <Settings className="w-5 h-5 mr-2 text-blue-600" />
                Export Configuration
              </h2>
              
              <div className="space-y-6">
                {/* Project Name */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Project Name
                  </label>
                  <input
                    type="text"
                    value={config.projectName}
                    onChange={(e) => setConfig({ ...config, projectName: e.target.value })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  />
                </div>

                {/* Framework Selection */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Framework
                  </label>
                  <div className="grid grid-cols-2 gap-3">
                    {(['react', 'next', 'vue', 'svelte'] as const).map((framework) => (
                      <button
                        key={framework}
                        onClick={() => setConfig({ ...config, framework })}
                        className={`p-3 text-left border rounded-lg transition-colors ${
                          config.framework === framework
                            ? 'border-blue-500 bg-blue-50 text-blue-700'
                            : 'border-gray-300 hover:border-gray-400'
                        }`}
                      >
                        <div className="font-medium capitalize">{framework}</div>
                        <div className="text-xs text-gray-500 mt-1">
                          {framework === 'react' && 'Single Page App'}
                          {framework === 'next' && 'Full-stack React'}
                          {framework === 'vue' && 'Progressive Framework'}
                          {framework === 'svelte' && 'Compile-time Framework'}
                        </div>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Styling Selection */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Styling
                  </label>
                  <div className="grid grid-cols-2 gap-3">
                    {(['tailwind', 'styled-components', 'css-modules', 'sass'] as const).map((styling) => (
                      <button
                        key={styling}
                        onClick={() => setConfig({ ...config, styling })}
                        className={`p-3 text-left border rounded-lg transition-colors ${
                          config.styling === styling
                            ? 'border-blue-500 bg-blue-50 text-blue-700'
                            : 'border-gray-300 hover:border-gray-400'
                        }`}
                      >
                        <div className="font-medium">{styling}</div>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Features */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-3">
                    Features
                  </label>
                  <div className="space-y-3">
                    {Object.entries(config.features).map(([feature, enabled]) => (
                      <label key={feature} className="flex items-center space-x-3">
                        <input
                          type="checkbox"
                          checked={enabled}
                          onChange={(e) => setConfig({
                            ...config,
                            features: { ...config.features, [feature]: e.target.checked }
                          })}
                          className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                        />
                        <div>
                          <div className="font-medium capitalize">{feature}</div>
                          <div className="text-xs text-gray-500">
                            {feature === 'typescript' && 'Type-safe development'}
                            {feature === 'testing' && 'Jest + Testing Library'}
                            {feature === 'accessibility' && 'WCAG AA compliance'}
                            {feature === 'seo' && 'Search engine optimization'}
                            {feature === 'pwa' && 'Progressive Web App'}
                          </div>
                        </div>
                      </label>
                    ))}
                  </div>
                </div>
              </div>

              <button
                onClick={() => setStep('preview')}
                disabled={elements.length === 0}
                className="w-full mt-6 bg-blue-600 text-white py-3 px-4 rounded-lg font-semibold hover:bg-blue-700 transition-colors flex items-center justify-center disabled:opacity-50 disabled:cursor-not-allowed"
              >
                <Code className="w-5 h-5 mr-2" />
                Preview Export
              </button>
              
              {elements.length === 0 && (
                <p className="text-center text-sm text-red-600 mt-2">
                  Create components in the builder first!
                </p>
              )}
            </div>

            {/* Benefits Panel */}
            <div className="bg-white rounded-xl shadow-lg p-6 border border-gray-200">
              <h2 className="text-xl font-semibold mb-6 flex items-center">
                <Zap className="w-5 h-5 mr-2 text-purple-600" />
                Export Benefits
              </h2>
              
              <div className="space-y-4">
                <div className="border border-gray-200 rounded-lg p-4">
                  <h3 className="font-semibold text-gray-900 mb-2">
                    🚀 Production-Ready Code
                  </h3>
                  <p className="text-gray-600 text-sm">
                    Get clean, optimized {config.framework.toUpperCase()} code that follows best practices and is ready for deployment.
                  </p>
                </div>

                <div className="border border-gray-200 rounded-lg p-4">
                  <h3 className="font-semibold text-gray-900 mb-2">
                    🎨 Modern Styling
                  </h3>
                  <p className="text-gray-600 text-sm">
                    Complete {config.styling} setup with design system, responsive utilities, and custom components.
                  </p>
                </div>

                <div className="border border-gray-200 rounded-lg p-4">
                  <h3 className="font-semibold text-gray-900 mb-2">
                    ⚡ Zero Vendor Lock-in
                  </h3>
                  <p className="text-gray-600 text-sm">
                    Unlike Framer or Webflow, you own the code completely. Modify, deploy, or migrate anywhere.
                  </p>
                </div>

                <div className="border border-gray-200 rounded-lg p-4">
                  <h3 className="font-semibold text-gray-900 mb-2">
                    📊 Performance Optimized
                  </h3>
                  <p className="text-gray-600 text-sm">
                    Automatic bundle optimization, lazy loading, and Core Web Vitals optimization built-in.
                  </p>
                </div>
              </div>

              {/* Live Stats */}
              <div className="mt-6 p-4 bg-gradient-to-r from-blue-50 to-purple-50 rounded-lg border border-blue-200">
                <h4 className="font-semibold text-blue-900 mb-2">📊 Your Project Stats</h4>
                <div className="grid grid-cols-2 gap-4 text-sm">
                  <div>
                    <span className="text-blue-700">Components:</span>
                    <div className="font-medium">{elements.length}</div>
                  </div>
                  <div>
                    <span className="text-blue-700">Framework:</span>
                    <div className="font-medium capitalize">{config.framework}</div>
                  </div>
                  <div>
                    <span className="text-blue-700">Est. Bundle:</span>
                    <div className="font-medium">~{Math.max(25, elements.length * 3)}KB</div>
                  </div>
                  <div>
                    <span className="text-blue-700">Features:</span>
                    <div className="font-medium">{Object.values(config.features).filter(Boolean).length}/5</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}

        {step === 'preview' && (
          <div className="max-w-4xl mx-auto">
            <div className="bg-white rounded-xl shadow-lg border border-gray-200 overflow-hidden">
              <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white p-6">
                <h2 className="text-2xl font-bold mb-2">Export Preview</h2>
                <p className="text-blue-100">{config.projectName} - {elements.length} components ready</p>
              </div>
              
              <div className="p-6">
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                  <div className="text-center">
                    <div className="bg-blue-100 text-blue-600 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-3">
                      <FileText className="w-6 h-6" />
                    </div>
                    <h3 className="font-semibold">~{Math.max(20, elements.length * 2)} Files</h3>
                    <p className="text-gray-600 text-sm">Complete project structure</p>
                  </div>
                  <div className="text-center">
                    <div className="bg-green-100 text-green-600 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-3">
                      <Zap className="w-6 h-6" />
                    </div>
                    <h3 className="font-semibold">99+ Score</h3>
                    <p className="text-gray-600 text-sm">Lighthouse performance</p>
                  </div>
                  <div className="text-center">
                    <div className="bg-purple-100 text-purple-600 w-12 h-12 rounded-full flex items-center justify-center mx-auto mb-3">
                      <Code className="w-6 h-6" />
                    </div>
                    <h3 className="font-semibold">Clean Code</h3>
                    <p className="text-gray-600 text-sm">Production-ready quality</p>
                  </div>
                </div>

                <div className="flex space-x-4">
                  <button
                    onClick={() => setStep('config')}
                    className="px-6 py-3 border border-gray-300 text-gray-700 rounded-lg font-semibold hover:bg-gray-50 transition-colors"
                  >
                    ← Back to Config
                  </button>
                  <button
                    onClick={handleExport}
                    disabled={loading || elements.length === 0}
                    className="flex-1 bg-gradient-to-r from-blue-600 to-purple-600 text-white py-3 px-6 rounded-lg font-semibold hover:from-blue-700 hover:to-purple-700 transition-colors flex items-center justify-center disabled:opacity-50"
                  >
                    {loading ? (
                      <>
                        <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white mr-2"></div>
                        Generating Code...
                      </>
                    ) : (
                      <>
                        <Rocket className="w-5 h-5 mr-2" />
                        Generate {config.framework.toUpperCase()} Project
                      </>
                    )}
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}

        {step === 'export' && exportResult && (
          <div className="max-w-6xl mx-auto">
            <div className="bg-white rounded-xl shadow-lg border border-gray-200 overflow-hidden">
              <div className="bg-gradient-to-r from-green-500 to-emerald-600 text-white p-6">
                <h2 className="text-2xl font-bold mb-2">🎉 Export Complete!</h2>
                <p className="text-green-100">{exportResult.message}</p>
              </div>
              
              <div className="p-6">
                <div className="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
                  <div className="bg-blue-50 p-4 rounded-lg text-center">
                    <div className="text-2xl font-bold text-blue-600">{exportResult.files?.length || 0}</div>
                    <div className="text-blue-700">Files Generated</div>
                  </div>
                  <div className="bg-green-50 p-4 rounded-lg text-center">
                    <div className="text-2xl font-bold text-green-600">
                      {exportResult.metadata ? (exportResult.metadata.totalSize / 1024).toFixed(1) : '0'}KB
                    </div>
                    <div className="text-green-700">Total Size</div>
                  </div>
                  <div className="bg-purple-50 p-4 rounded-lg text-center">
                    <div className="text-2xl font-bold text-purple-600">{config.framework.toUpperCase()}</div>
                    <div className="text-purple-700">Framework</div>
                  </div>
                  <div className="bg-orange-50 p-4 rounded-lg text-center">
                    <div className="text-2xl font-bold text-orange-600">{elements.length}</div>
                    <div className="text-orange-700">Components</div>
                  </div>
                </div>

                <div className="mb-6">
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-lg font-semibold">Generated Files</h3>
                    <button
                      onClick={downloadAsZip}
                      className="bg-blue-600 text-white px-4 py-2 rounded-lg font-medium hover:bg-blue-700 transition-colors flex items-center"
                    >
                      <Download className="w-4 h-4 mr-2" />
                      Download ZIP
                    </button>
                  </div>
                  
                  {exportResult.files && (
                    <div className="max-h-96 overflow-y-auto border border-gray-200 rounded-lg">
                      {exportResult.files.map((file: any, index: number) => (
                        <div key={index} className="border-b border-gray-100 last:border-b-0 p-3 hover:bg-gray-50">
                          <div className="flex items-center justify-between">
                            <div className="flex-1">
                              <div className="font-mono text-sm text-blue-600">{file.path}</div>
                              <div className="text-xs text-gray-500 mt-1">
                                {file.type} • {file.size ? (file.size / 1024).toFixed(1) : '0'}KB
                              </div>
                            </div>
                            <button className="text-gray-400 hover:text-gray-600 ml-4">
                              <Code className="w-4 h-4" />
                            </button>
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>

                <div className="flex space-x-4">
                  <button
                    onClick={() => {
                      setStep('config')
                      setExportResult(null)
                    }}
                    className="flex-1 bg-gray-100 text-gray-700 py-3 px-4 rounded-lg font-semibold hover:bg-gray-200 transition-colors"
                  >
                    Create Another Export
                  </button>
                  <button
                    onClick={() => window.open('/builder', '_blank')}
                    className="flex-1 bg-blue-600 text-white py-3 px-4 rounded-lg font-semibold hover:bg-blue-700 transition-colors"
                  >
                    ← Back to Builder
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}